[tool.pytest.ini_options]
minversion = "6.2"
addopts = "-ra"
testpaths = ["tests"]

[tool.coverage.report]
exclude_lines = [
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "pragma: nocover",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
omit = [
    "tests/*",
]

[tool.mypy]
files = ["src/**/*.py", "tests/**/*.py"]
ignore_missing_imports = true

[tool.ruff]
exclude = [".git", ".venv", "build", "dist", "node_modules"]
line-length = 88
indent-width = 4
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E501"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
known-first-party = ["latentis"]
force-sort-within-sections = true
combine-as-imports = true

[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[dependency-groups]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "transformers",
    "datasets",
    "torchvision",
    "mkdocs",
    "mkdocs-material",
    "mike",
]

[project]
name = "latentis"
dependencies = [
    "torchmetrics",
    "scikit-learn",
    "backports.strenum",
    "python-dotenv",
    "GitPython",
    "matplotlib",
    "plotly",
    "faiss-cpu",
    "pandas",
    "fire",
    "lightning",
    "h5py",
    "transformers",
    "gin-config",
    "dvc",
    "dvc[gdrive]",
    "tueplots",
    "requests",
]

dynamic = ["version"]
description = "A Python package for analyzing and transforming neural latent spaces."
readme = "README.md"
urls = { Repository = "https://github.com/flegyas/latentis" }
maintainers = [{ name = "Valentino Maiorca", email = "valentino@maiorca.xyz" }]
requires-python = ">=3.9"
keywords = [
    "neural networks",
    "latent spaces",
    "dimensionality reduction",
    "clustering",
    "visualization",
    "python",
]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Visualization",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
