name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.label }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    environment: release
    permissions:
      id-token: write

    steps:
      - name: Set release notes tag
        run: |
          export RELEASE_TAG_VERSION=${{ github.event.release.tag_name }}
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION%.*}">> $GITHUB_ENV

      - name: Echo release notes tag
        run: |
          echo "${RELEASE_TAG_VERSION}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build the project
        run: uvx --from build pyproject-build --installer uv

      - name: Check metadata
        run: uvx twine check dist/*

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
