name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9']
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/

    name: ${{ matrix.label }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      # extract the first two digits from the release note
      - name: Set release notes tag
        run: |
          export RELEASE_TAG_VERSION=${{ github.event.release.tag_name }}
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION%.*}">> $GITHUB_ENV

      - name: Echo release notes tag
        run: |
          echo "${RELEASE_TAG_VERSION}"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check working directory status
        run: git status

      - name: Restore working directory (env.yaml Python version)
        run: git checkout .

      - name: Build SDist and wheel
        run: pipx run build

      - name: Check metadata
        run: pipx run twine check dist/*

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Build docs website
        shell: bash -l {0}
        run: |
          git config user.name ci-bot
          git config user.email ci-bot@ci.com
          mike deploy --push --rebase --update-aliases ${RELEASE_TAG_VERSION} latest
