name: tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        include:
          - os: ubuntu-latest
            label: linux-64

      fail-fast: false

    name: ${{ matrix.label }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Run pre-commits
        run: |
          uv run pre-commit install
          uv run pre-commit run -v --all-files --show-diff-on-failure

      - name: Run tests and collect coverage
        run: |
          uv run pytest --cov --cov-report xml:coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
